### ISSUE TITLE
U8 Cannot be installed in 32-bit Windows Operation System

### ISSUE THREAD

**Issue by LBlingbomc** [lingboCoop/YongYouErpForLingBoMc#3]
No longer support 32-bit System.

![tim 20190103162055](https://user-images.githubusercontent.com/45930507/50628609-d0c8ff80-0f73-11e9-8d6a-85519a930a5f.png)

**Comment by SONGLIN-LBMC** [comment]
可以尝试在程序快捷方式上点击右键——属性——兼容性——勾选“以兼容模式运行这个程序”下拉菜单中选择windowsXP（Service pack 3），同时勾选以管理员身份运行此程序——确定。 重新打开程序进行尝试一下。

**Comment by SONGLIN-LBMC** [comment]
是的一样的。在安装前，在这个安装程序的快捷键上。在改一下兼容性后，在开始安装U8程序。看一下还会有提示不?

**Comment by LBlingbomc** [comment]
>           是的一样的。在安装前，在这个安装程序的快捷键上。在改一下兼容性后，在开始安装U8程序。看一下还会有提示不?
还是会的
@SONGLIN-LBMC

**Comment by SONGLIN-LBMC** [comment]
能给我给截图吗？

**Comment by LBlingbomc** [comment]
@SONGLIN-LBMC 
三张照片如下，没有让我进入选择系统环境检测的环节
![img_20190104_105530](https://user-images.githubusercontent.com/45930507/50671908-d1af6f00-100f-11e9-97b1-90a67547da74.jpg)
![img_20190104_105611](https://user-images.githubusercontent.com/45930507/50671910-d2e09c00-100f-11e9-8a50-0be323d40b3c.jpg)
![img_20190104_105608](https://user-images.githubusercontent.com/45930507/50671911-d4aa5f80-100f-11e9-9e0f-051e80b72557.jpg)

**Comment by SONGLIN-LBMC** [comment]
电脑的.net framework 3.5  和IIS 有没有启用

**Comment by SONGLIN-LBMC** [comment]
你可以参照https://wenku.baidu.com/view/fd15d048f111f18582d05a29.html这个文档来试一下。

**Comment by SONGLIN-LBMC** [comment]
要是还不行，只能到时候现场看一下了。

**Comment by LBlingbomc** [comment]
公司64位的电脑应该是都安装成功了，32位操作系统的电脑应该是没有安装上。
@SONGLIN-LBMC

**Comment by wuhan-lbmc** [comment]
丁工，重新提供版本，经测试在32位系统上可以使用，具体下载地址私信发给您

**Comment by LBlingbomc** [comment]
的确可以
