### ISSUE TITLE
提供简单的导入模板可行性

### ISSUE THREAD

**Issue by caizhongli** [lingboCoop/YongYouErpForLingBoMc#6]
1）目前提供导入模板选项太多，无法取舍必填项和选填项，建议是否可以删除一些不必要的选项。
2）版本代号只能取整数，目前我司的文件版本和PCB版本均为V0.x和V1.0.
3)子母件在清单模板中如何衔接，请用友方给予示例，因我司清单结构相对复杂，请综合考虑并及时给予合适建议及文档，便于进入状态整理清单，谢谢！

**Comment by lingbo-xuld** [comment]
关于第2）点，我们定义的版本号：V0.X或则VX.X，第一个X>=1

**Comment by lingbo-xuld** [comment]
Ok，我们原来也是整数，说明中标注为VX.X

 

Best Regards！

 

许良栋（Liangdong Xu）

Tel. 0510 66078684

Email: ld.xu@lingbomc.com <mailto:ld.xu@lingbomc.com> 

http://www.lingbo-mc.com

 

无锡凌博电子技术有限公司

地址：无锡市滨湖区绣溪道59号交大创意园10号楼

 

Wuxi Lingbo Electronic Technologies Co.,Ltd.

Add：Building 10, JiaoTong University Creative Park, No.59 Xiuxi Road,Binhu District, Wuxi, PR China

 

发件人: noreply@github.com [mailto:noreply@github.com] 代表 wuhan-lbmc
发送时间: 2019年1月6日 20:27
收件人: lingboCoop/YongYouErpForLingBoMc
抄送: lingbo-xuld; Comment
主题: Re: [lingboCoop/YongYouErpForLingBoMc] 提供简单的导入模板可行性 (#6)

 

版本号需要填写整数，在版本说明中填写VX.X
 <https://github.com/lingboCoop/YongYouErpForLingBoMc/files/2730447/default.xlsx> 存货档案模板.xlsx
BOM <https://github.com/lingboCoop/YongYouErpForLingBoMc/files/2730448/BOM.xlsx> 清单.xlsx

**Comment by caizhongli** [comment]
![image](https://user-images.githubusercontent.com/46334333/50744241-41b23500-125c-11e9-9aaa-60570cbdffa0.png)
这是之前的清单导入模板，请问你们的工程图号，备注，可选件及序号，项序排列在哪

**Comment by LBlingbomc** [comment]
@caizhongli @LIYU911127 工程图号好像是在子件工程图号列 
序列是在子件行号里面，
可选件在可选否里面是一个Boolean值，
备注的话您先写在子件备注里面。
用友的BOM和方天的BOM模板思想不一样，方天是一纯树，用友是一棵展开的二维树。所以思想可能要转变下。

**Comment by wuhan-lbmc** [comment]
可能我简化的模板缺少你们想要的东西，现在使用标准的导入模板，我这边提供帮助文档已提交给丁工，请相关人员下载查看

**Comment by LBlingbomc** [comment]
@caizhongli @LIYU911127 ERP给您两位的简易模板不要使用，使用上次给出的详细模板就行，详细模板中
序列是在子件行号里面，
可选件在可选否里面是一个Boolean值，
备注的话先写在子件备注里面。
插件位写在自定义项一里面。
